/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.21.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.Ability;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-04-24T18:09:55.929218400+03:00[Europe/Bucharest]", comments = "Generator version: 7.21.0")
@Validated
@Tag(name = "abilities", description = "the abilities API")
public interface AbilitiesApi {

    default AbilitiesApiDelegate getDelegate() {
        return new AbilitiesApiDelegate() {};
    }

    String PATH_ABILITIES_GET = "/abilities";
    /**
     * GET /abilities : Get abilities
     *
     * @return Ability list (status code 200)
     */
    @Operation(
        operationId = "abilitiesGet",
        summary = "Get abilities",
        responses = {
            @ApiResponse(responseCode = "200", description = "Ability list", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Ability.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = AbilitiesApi.PATH_ABILITIES_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<List<Ability>> abilitiesGet(
        
    ) {
        return getDelegate().abilitiesGet();
    }

}
