/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.21.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.springframework.lang.Nullable;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-04-24T18:09:55.929218400+03:00[Europe/Bucharest]", comments = "Generator version: 7.21.0")
@Validated
@Tag(name = "ability-packs", description = "the ability-packs API")
public interface AbilityPacksApi {

    default AbilityPacksApiDelegate getDelegate() {
        return new AbilityPacksApiDelegate() {};
    }

    String PATH_ABILITY_PACKS_IMPORT_POST = "/ability-packs/import";
    /**
     * POST /ability-packs/import : Import ability pack
     *
     * @param file  (optional)
     * @return Ability pack imported (status code 200)
     */
    @Operation(
        operationId = "abilityPacksImportPost",
        summary = "Import ability pack",
        responses = {
            @ApiResponse(responseCode = "200", description = "Ability pack imported")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AbilityPacksApi.PATH_ABILITY_PACKS_IMPORT_POST,
        consumes = { "multipart/form-data" }
    )
    default ResponseEntity<Void> abilityPacksImportPost(
        @Parameter(name = "file", description = "") @RequestPart(value = "file", required = false) MultipartFile file
    ) {
        return getDelegate().abilityPacksImportPost(file);
    }

}
