/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.21.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.CreateMatchRequest;
import org.openapitools.model.Match;
import org.openapitools.model.MatchState;
import org.openapitools.model.MatchStatus;
import org.openapitools.model.MatchesMatchIdJoinPostRequest;
import org.openapitools.model.MatchesMatchIdRoundsRoundIdAbilitiesActivatePostRequest;
import org.openapitools.model.MatchesMatchIdRoundsRoundIdLockPostRequest;
import org.openapitools.model.MatchesMatchIdRoundsRoundIdRollPostRequest;
import org.springframework.lang.Nullable;
import org.openapitools.model.Round;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-04-24T18:09:55.929218400+03:00[Europe/Bucharest]", comments = "Generator version: 7.21.0")
@Validated
@Tag(name = "matches", description = "the matches API")
public interface MatchesApi {

    default MatchesApiDelegate getDelegate() {
        return new MatchesApiDelegate() {};
    }

    String PATH_MATCHES_GET = "/matches";
    /**
     * GET /matches : Get matches (optional filter)
     *
     * @param status  (optional)
     * @return Match list (status code 200)
     */
    @Operation(
        operationId = "matchesGet",
        summary = "Get matches (optional filter)",
        responses = {
            @ApiResponse(responseCode = "200", description = "Match list", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Match.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = MatchesApi.PATH_MATCHES_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<List<Match>> matchesGet(
        @Parameter(name = "status", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "status", required = false) @Nullable MatchStatus status
    ) {
        return getDelegate().matchesGet(status);
    }


    String PATH_MATCHES_MATCH_ID_GET = "/matches/{matchId}";
    /**
     * GET /matches/{matchId} : Get match
     *
     * @param matchId  (required)
     * @return Match found (status code 200)
     */
    @Operation(
        operationId = "matchesMatchIdGet",
        summary = "Get match",
        responses = {
            @ApiResponse(responseCode = "200", description = "Match found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Match.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = MatchesApi.PATH_MATCHES_MATCH_ID_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<Match> matchesMatchIdGet(
        @Parameter(name = "matchId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("matchId") String matchId
    ) {
        return getDelegate().matchesMatchIdGet(matchId);
    }


    String PATH_MATCHES_MATCH_ID_JOIN_POST = "/matches/{matchId}/join";
    /**
     * POST /matches/{matchId}/join : Join match
     *
     * @param matchId  (required)
     * @param matchesMatchIdJoinPostRequest  (optional)
     * @return Player joined (status code 200)
     */
    @Operation(
        operationId = "matchesMatchIdJoinPost",
        summary = "Join match",
        responses = {
            @ApiResponse(responseCode = "200", description = "Player joined")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = MatchesApi.PATH_MATCHES_MATCH_ID_JOIN_POST,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> matchesMatchIdJoinPost(
        @Parameter(name = "matchId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("matchId") String matchId,
        @Parameter(name = "MatchesMatchIdJoinPostRequest", description = "") @Valid @RequestBody(required = false) @Nullable MatchesMatchIdJoinPostRequest matchesMatchIdJoinPostRequest
    ) {
        return getDelegate().matchesMatchIdJoinPost(matchId, matchesMatchIdJoinPostRequest);
    }


    String PATH_MATCHES_MATCH_ID_REPLAY_EXPORT_GET = "/matches/{matchId}/replay/export";
    /**
     * GET /matches/{matchId}/replay/export : Export replay
     *
     * @param matchId  (required)
     * @return Replay file (status code 200)
     */
    @Operation(
        operationId = "matchesMatchIdReplayExportGet",
        summary = "Export replay",
        responses = {
            @ApiResponse(responseCode = "200", description = "Replay file")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = MatchesApi.PATH_MATCHES_MATCH_ID_REPLAY_EXPORT_GET
    )
    default ResponseEntity<Void> matchesMatchIdReplayExportGet(
        @Parameter(name = "matchId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("matchId") String matchId
    ) {
        return getDelegate().matchesMatchIdReplayExportGet(matchId);
    }


    String PATH_MATCHES_MATCH_ID_ROUNDS_ROUND_ID_ABILITIES_ACTIVATE_POST = "/matches/{matchId}/rounds/{roundId}/abilities/activate";
    /**
     * POST /matches/{matchId}/rounds/{roundId}/abilities/activate : Activate ability
     *
     * @param matchId  (required)
     * @param roundId  (required)
     * @param matchesMatchIdRoundsRoundIdAbilitiesActivatePostRequest  (optional)
     * @return Ability activated (status code 200)
     */
    @Operation(
        operationId = "matchesMatchIdRoundsRoundIdAbilitiesActivatePost",
        summary = "Activate ability",
        responses = {
            @ApiResponse(responseCode = "200", description = "Ability activated")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = MatchesApi.PATH_MATCHES_MATCH_ID_ROUNDS_ROUND_ID_ABILITIES_ACTIVATE_POST,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> matchesMatchIdRoundsRoundIdAbilitiesActivatePost(
        @Parameter(name = "matchId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("matchId") String matchId,
        @Parameter(name = "roundId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("roundId") String roundId,
        @Parameter(name = "MatchesMatchIdRoundsRoundIdAbilitiesActivatePostRequest", description = "") @Valid @RequestBody(required = false) @Nullable MatchesMatchIdRoundsRoundIdAbilitiesActivatePostRequest matchesMatchIdRoundsRoundIdAbilitiesActivatePostRequest
    ) {
        return getDelegate().matchesMatchIdRoundsRoundIdAbilitiesActivatePost(matchId, roundId, matchesMatchIdRoundsRoundIdAbilitiesActivatePostRequest);
    }


    String PATH_MATCHES_MATCH_ID_ROUNDS_ROUND_ID_GET = "/matches/{matchId}/rounds/{roundId}";
    /**
     * GET /matches/{matchId}/rounds/{roundId} : Get round
     *
     * @param matchId  (required)
     * @param roundId  (required)
     * @return Round data (status code 200)
     */
    @Operation(
        operationId = "matchesMatchIdRoundsRoundIdGet",
        summary = "Get round",
        responses = {
            @ApiResponse(responseCode = "200", description = "Round data", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Round.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = MatchesApi.PATH_MATCHES_MATCH_ID_ROUNDS_ROUND_ID_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<Round> matchesMatchIdRoundsRoundIdGet(
        @Parameter(name = "matchId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("matchId") String matchId,
        @Parameter(name = "roundId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("roundId") String roundId
    ) {
        return getDelegate().matchesMatchIdRoundsRoundIdGet(matchId, roundId);
    }


    String PATH_MATCHES_MATCH_ID_ROUNDS_ROUND_ID_LOCK_POST = "/matches/{matchId}/rounds/{roundId}/lock";
    /**
     * POST /matches/{matchId}/rounds/{roundId}/lock : Lock dice
     *
     * @param matchId  (required)
     * @param roundId  (required)
     * @param matchesMatchIdRoundsRoundIdLockPostRequest  (optional)
     * @return Dice locked (status code 200)
     */
    @Operation(
        operationId = "matchesMatchIdRoundsRoundIdLockPost",
        summary = "Lock dice",
        responses = {
            @ApiResponse(responseCode = "200", description = "Dice locked")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = MatchesApi.PATH_MATCHES_MATCH_ID_ROUNDS_ROUND_ID_LOCK_POST,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> matchesMatchIdRoundsRoundIdLockPost(
        @Parameter(name = "matchId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("matchId") String matchId,
        @Parameter(name = "roundId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("roundId") String roundId,
        @Parameter(name = "MatchesMatchIdRoundsRoundIdLockPostRequest", description = "") @Valid @RequestBody(required = false) @Nullable MatchesMatchIdRoundsRoundIdLockPostRequest matchesMatchIdRoundsRoundIdLockPostRequest
    ) {
        return getDelegate().matchesMatchIdRoundsRoundIdLockPost(matchId, roundId, matchesMatchIdRoundsRoundIdLockPostRequest);
    }


    String PATH_MATCHES_MATCH_ID_ROUNDS_ROUND_ID_RESOLVE_POST = "/matches/{matchId}/rounds/{roundId}/resolve";
    /**
     * POST /matches/{matchId}/rounds/{roundId}/resolve : Resolve round
     *
     * @param matchId  (required)
     * @param roundId  (required)
     * @return Round resolved (status code 200)
     */
    @Operation(
        operationId = "matchesMatchIdRoundsRoundIdResolvePost",
        summary = "Resolve round",
        responses = {
            @ApiResponse(responseCode = "200", description = "Round resolved")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = MatchesApi.PATH_MATCHES_MATCH_ID_ROUNDS_ROUND_ID_RESOLVE_POST
    )
    default ResponseEntity<Void> matchesMatchIdRoundsRoundIdResolvePost(
        @Parameter(name = "matchId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("matchId") String matchId,
        @Parameter(name = "roundId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("roundId") String roundId
    ) {
        return getDelegate().matchesMatchIdRoundsRoundIdResolvePost(matchId, roundId);
    }


    String PATH_MATCHES_MATCH_ID_ROUNDS_ROUND_ID_ROLL_POST = "/matches/{matchId}/rounds/{roundId}/roll";
    /**
     * POST /matches/{matchId}/rounds/{roundId}/roll : Roll dice
     *
     * @param matchId  (required)
     * @param roundId  (required)
     * @param matchesMatchIdRoundsRoundIdRollPostRequest  (optional)
     * @return Dice rolled (status code 200)
     */
    @Operation(
        operationId = "matchesMatchIdRoundsRoundIdRollPost",
        summary = "Roll dice",
        responses = {
            @ApiResponse(responseCode = "200", description = "Dice rolled")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = MatchesApi.PATH_MATCHES_MATCH_ID_ROUNDS_ROUND_ID_ROLL_POST,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> matchesMatchIdRoundsRoundIdRollPost(
        @Parameter(name = "matchId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("matchId") String matchId,
        @Parameter(name = "roundId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("roundId") String roundId,
        @Parameter(name = "MatchesMatchIdRoundsRoundIdRollPostRequest", description = "") @Valid @RequestBody(required = false) @Nullable MatchesMatchIdRoundsRoundIdRollPostRequest matchesMatchIdRoundsRoundIdRollPostRequest
    ) {
        return getDelegate().matchesMatchIdRoundsRoundIdRollPost(matchId, roundId, matchesMatchIdRoundsRoundIdRollPostRequest);
    }


    String PATH_MATCHES_MATCH_ID_START_POST = "/matches/{matchId}/start";
    /**
     * POST /matches/{matchId}/start : Start match
     *
     * @param matchId  (required)
     * @return Match started (status code 200)
     */
    @Operation(
        operationId = "matchesMatchIdStartPost",
        summary = "Start match",
        responses = {
            @ApiResponse(responseCode = "200", description = "Match started")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = MatchesApi.PATH_MATCHES_MATCH_ID_START_POST
    )
    default ResponseEntity<Void> matchesMatchIdStartPost(
        @Parameter(name = "matchId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("matchId") String matchId
    ) {
        return getDelegate().matchesMatchIdStartPost(matchId);
    }


    String PATH_MATCHES_MATCH_ID_STATE_GET = "/matches/{matchId}/state";
    /**
     * GET /matches/{matchId}/state : Get match state
     *
     * @param matchId  (required)
     * @return Match state (status code 200)
     */
    @Operation(
        operationId = "matchesMatchIdStateGet",
        summary = "Get match state",
        responses = {
            @ApiResponse(responseCode = "200", description = "Match state", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = MatchState.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = MatchesApi.PATH_MATCHES_MATCH_ID_STATE_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<MatchState> matchesMatchIdStateGet(
        @Parameter(name = "matchId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("matchId") String matchId
    ) {
        return getDelegate().matchesMatchIdStateGet(matchId);
    }


    String PATH_MATCHES_POST = "/matches";
    /**
     * POST /matches : Create match
     *
     * @param createMatchRequest  (optional)
     * @return Match created (status code 201)
     */
    @Operation(
        operationId = "matchesPost",
        summary = "Create match",
        responses = {
            @ApiResponse(responseCode = "201", description = "Match created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Match.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = MatchesApi.PATH_MATCHES_POST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Match> matchesPost(
        @Parameter(name = "CreateMatchRequest", description = "") @Valid @RequestBody(required = false) @Nullable CreateMatchRequest createMatchRequest
    ) {
        return getDelegate().matchesPost(createMatchRequest);
    }

}
