/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.21.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.Ability;
import org.openapitools.model.CreatePlayerRequest;
import org.springframework.lang.Nullable;
import org.openapitools.model.Player;
import org.openapitools.model.PlayerStats;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-04-24T18:09:55.929218400+03:00[Europe/Bucharest]", comments = "Generator version: 7.21.0")
@Validated
@Tag(name = "players", description = "the players API")
public interface PlayersApi {

    default PlayersApiDelegate getDelegate() {
        return new PlayersApiDelegate() {};
    }

    String PATH_PLAYERS_GET = "/players";
    /**
     * GET /players : Get all players
     *
     * @return List of players (status code 200)
     */
    @Operation(
        operationId = "playersGet",
        summary = "Get all players",
        responses = {
            @ApiResponse(responseCode = "200", description = "List of players", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Player.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = PlayersApi.PATH_PLAYERS_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<List<Player>> playersGet(
        
    ) {
        return getDelegate().playersGet();
    }


    String PATH_PLAYERS_PLAYER_ID_ABILITIES_GET = "/players/{playerId}/abilities";
    /**
     * GET /players/{playerId}/abilities : Get player abilities
     *
     * @param playerId  (required)
     * @return Player abilities (status code 200)
     */
    @Operation(
        operationId = "playersPlayerIdAbilitiesGet",
        summary = "Get player abilities",
        responses = {
            @ApiResponse(responseCode = "200", description = "Player abilities", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Ability.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = PlayersApi.PATH_PLAYERS_PLAYER_ID_ABILITIES_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<List<Ability>> playersPlayerIdAbilitiesGet(
        @Parameter(name = "playerId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("playerId") String playerId
    ) {
        return getDelegate().playersPlayerIdAbilitiesGet(playerId);
    }


    String PATH_PLAYERS_PLAYER_ID_AVATAR_POST = "/players/{playerId}/avatar";
    /**
     * POST /players/{playerId}/avatar : Upload avatar
     *
     * @param playerId  (required)
     * @param file  (optional)
     * @return Avatar uploaded (status code 200)
     */
    @Operation(
        operationId = "playersPlayerIdAvatarPost",
        summary = "Upload avatar",
        responses = {
            @ApiResponse(responseCode = "200", description = "Avatar uploaded")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = PlayersApi.PATH_PLAYERS_PLAYER_ID_AVATAR_POST,
        consumes = { "multipart/form-data" }
    )
    default ResponseEntity<Void> playersPlayerIdAvatarPost(
        @Parameter(name = "playerId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("playerId") String playerId,
        @Parameter(name = "file", description = "") @RequestPart(value = "file", required = false) MultipartFile file
    ) {
        return getDelegate().playersPlayerIdAvatarPost(playerId, file);
    }


    String PATH_PLAYERS_PLAYER_ID_GET = "/players/{playerId}";
    /**
     * GET /players/{playerId} : Get player
     *
     * @param playerId  (required)
     * @return Player found (status code 200)
     */
    @Operation(
        operationId = "playersPlayerIdGet",
        summary = "Get player",
        responses = {
            @ApiResponse(responseCode = "200", description = "Player found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Player.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = PlayersApi.PATH_PLAYERS_PLAYER_ID_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<Player> playersPlayerIdGet(
        @Parameter(name = "playerId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("playerId") String playerId
    ) {
        return getDelegate().playersPlayerIdGet(playerId);
    }


    String PATH_PLAYERS_PLAYER_ID_STATS_GET = "/players/{playerId}/stats";
    /**
     * GET /players/{playerId}/stats : Get player stats
     *
     * @param playerId  (required)
     * @return Player stats (status code 200)
     */
    @Operation(
        operationId = "playersPlayerIdStatsGet",
        summary = "Get player stats",
        responses = {
            @ApiResponse(responseCode = "200", description = "Player stats", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PlayerStats.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = PlayersApi.PATH_PLAYERS_PLAYER_ID_STATS_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<PlayerStats> playersPlayerIdStatsGet(
        @Parameter(name = "playerId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("playerId") String playerId
    ) {
        return getDelegate().playersPlayerIdStatsGet(playerId);
    }


    String PATH_PLAYERS_POST = "/players";
    /**
     * POST /players : Create player
     *
     * @param createPlayerRequest  (required)
     * @return Player created (status code 201)
     */
    @Operation(
        operationId = "playersPost",
        summary = "Create player",
        responses = {
            @ApiResponse(responseCode = "201", description = "Player created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Player.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = PlayersApi.PATH_PLAYERS_POST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Player> playersPost(
        @Parameter(name = "CreatePlayerRequest", description = "", required = true) @Valid @RequestBody CreatePlayerRequest createPlayerRequest
    ) {
        return getDelegate().playersPost(createPlayerRequest);
    }

}
